/**
 * Sindh's 29 districts and 125 tehsils, sourced from UN OCHA's official
 * Pakistan Subnational Administrative Boundaries dataset (COD-AB,
 * data.humdata.org/dataset/cod-ab-pak). Kept in exact sync with the village
 * dataset in the backend (backend/app/data/sindh_villages.json), which was
 * generated by spatially matching OpenStreetMap populated-place points
 * against these same tehsil boundary polygons -- using a different naming
 * source here would silently break that matching.
 */
export const SINDH_DISTRICTS_TEHSILS: Record<string, string[]> = {
  "Badin": ["Badin", "Matli", "Shaheed Fazil Rahu", "Talhar", "Tando Bago"],
  "Central Karachi": ["Gulberg Town", "Liaqatabad Town", "New Karachi Town", "North Nazimabad Town"],
  "Dadu": ["Dadu", "Johi", "Khairpur Nathan Shah", "Mehar"],
  "East Karachi": ["Gulshan Iqbal Town", "Jamshaid Town"],
  "Ghotki": ["Daharki", "Ghotki", "Khangarh", "Mirpur Mathelo", "Ubauro"],
  "Hyderabad": ["Hyderabad", "Hyderabad City", "Latifabad", "Qasimabad"],
  "Jacobabad": ["Garhi Khairo", "Jacobabad", "Thul"],
  "Jamshoro": ["Kotri", "Manjhand", "Sehwan Sharif", "Thano Bula Khan"],
  "Kambar Shahdad Kot": ["Meero Khan", "Nasir Abad", "Qambar Ali Khan", "Qubo Saeed Khan", "Shahdad Kot", "Sijawal Junejo", "Warah"],
  "Kashmore": ["Kandh Kot", "Kashmore", "Tangwani"],
  "Khairpur": ["Faiz Ganj", "Gambat", "Khairpur", "Kingri", "Kot Diji", "Nara", "Sobho Dero", "Thari Meer Wah"],
  "Korangi Karachi": ["Korangi Town", "Landhi Town", "Shah Faisal Town"],
  "Larkana": ["Baqrani", "Dokri", "Larkana", "Rato Dero"],
  "Malir Karachi": ["Bin Qasim Town", "Gadap Town", "Malir Town"],
  "Matiari": ["Hala", "Matiari", "Saeedabad"],
  "Mirpur Khas": ["Digri", "Hussain Bux Muree", "Jhudo", "Kot Ghulam Muhammad", "Mirpur Khas", "Shuja Abad", "Sindhri"],
  "Naushahro Feroze": ["Bhiria", "Kandiaro", "Mehrab Pur", "Moro", "Naushahro Feroze"],
  "Sanghar": ["Jam Nawaz Ali", "Khipro", "Sanghar", "Shahdadpur", "Sinjhoro", "Tando Adam"],
  "Shaheed Benazir Abad": ["Daulat Pur", "Daur", "Nawabshah", "Sakrand"],
  "Shikarpur": ["Garhi Yasin", "Khanpur", "Lakhi", "Shikarpur"],
  "South Karachi": ["Kemari Town", "Liyari Town", "Saddar Town"],
  "Sujawal": ["Jati", "Kharo Chan", "Mirpur Bathoro", "Shah Bunder", "Sujawal"],
  "Sukkur": ["New Sukkur", "Pano Aqil", "Rohri", "Salehpat", "Sukkur"],
  "Tando Allahyar": ["Chamber", "Jhando Mari", "Tando Allahyar"],
  "Tando Muhammad Khan": ["Bulri Shah Karim", "Tando Ghulam Hyder", "Tando Muhammad Khan"],
  "Tharparkar": ["Chachro", "Dahli", "Diplo", "Islam Kot", "Kaloi", "Mithi", "Nagar Parkar"],
  "Thatta": ["Ghorabari", "Keti Bunder", "Mirpur Sakro", "Thatta"],
  "Umer Kot": ["Kunri", "Pithoro", "Samaro", "Umer Kot"],
  "West Karachi": ["Baldia Town", "Orangi Town", "Site Town"],
};

export const SINDH_DISTRICTS = Object.keys(SINDH_DISTRICTS_TEHSILS).sort();
